/*
 * Copyright 2016 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.2.4'
        classpath 'io.franzbecker:gradle-lombok:3.1.0'
        classpath 'io.spring.gradle:dependency-management-plugin:1.0.8.RELEASE'
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.1.5.RELEASE'
        classpath 'org.ajoberstar.grgit:grgit-core:4.1.1'
    }
}

apply plugin: 'java'
apply plugin: 'idea'

group = 'com.linecorp.bot'
// Procfileはbuild/libs/insider-game-bot-*.jarをワイルドカードで拾う
version = '2.7.0-SNAPSHOT'

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.franzbecker.gradle-lombok'
    apply plugin: 'io.spring.dependency-management'

    if (new File("${project.rootDir}/.git").exists()) {
        logger.info("There's .git directory. Create git.properties.")
        apply plugin: 'com.gorylenko.gradle-git-properties'
    } else {
        logger.warn("There's no .git directory. Can't create git.properties.")
    }

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    group = rootProject.group
    version = rootProject.version

    ext['guava.version'] = '28.0-jre'
    ext['okhttp3.version'] = '3.14.2'
    ext['retrofit.version'] = '2.6.0'

    dependencyManagement {
        imports {
            mavenBom 'io.spring.platform:platform-bom:Cairo-RELEASE'
            mavenBom 'org.springframework.boot:spring-boot-dependencies:2.1.5.RELEASE'
        }

        dependencies {
            dependency 'com.github.stefanbirkner:system-rules:1.19.0'
            dependency 'com.squareup.okhttp3:logging-interceptor:' + ext['okhttp3.version']
            dependency 'com.squareup.okhttp3:mockwebserver:' + ext['okhttp3.version']
            dependencySet(group: 'com.squareup.retrofit2', version: ext['retrofit.version']) {
                entry 'converter-jackson'
                entry 'retrofit'
            }
            dependency 'org.assertj:assertj-core:3.12.1'
            dependency 'org.projectlombok:lombok:1.18.34'
        }
    }

    dependencies {
        compileOnly 'org.springframework.boot:spring-boot-configuration-processor'
        testImplementation 'com.google.guava:guava'
        testImplementation 'com.github.stefanbirkner:system-rules'
        testImplementation 'com.squareup.okhttp3:mockwebserver'
        testImplementation 'org.hibernate:hibernate-validator'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.boot:spring-boot-starter-logging'
    }

    compileJava.dependsOn(processResources)

    jar {
        manifest {
            attributes 'Implementation-Title': project.name,
                'Implementation-Version': version
        }
    }

    lombok {
        version = '1.18.34'
    }

    compileJava {
        options.compilerArgs << '-Xlint:all' << '-Xlint:deprecation' << '-Werror' << '-Xlint:-processing' << '-parameters'
    }

    project.plugins.withType(org.springframework.boot.gradle.plugin.SpringBootPlugin) {
        bootRun {
            systemProperties System.properties
        }
    }
}

